### ISSUE TITLE
Setup Pull Request Website Previews

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/handbook#6]
As a contributor, I want pull requests to the handbook to automatically generate a hosted preview so I can easily review changes before they are merged.

---

## 🧠 Context

On the [[main CCSS website](https://github.com/CarletonComputerScienceSociety/website)](https://github.com/CarletonComputerScienceSociety/website), we have GitHub Actions set up to deploy a **preview version** of the site using Hugo and Surge whenever a pull request is opened.

We would like to add **similar preview support for the Docusaurus-based handbook site**.

The existing action looks like this:

```yaml
name: Build and Deploy PR Preview to Surge

on:
  pull_request:

jobs:
  build_preview:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.128.0'
          extended: true

      - name: Setup base URL env var
        run: |
          export PRNUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") 
          echo BASEURL="https://carletoncomputersciencesociety-website-build_preview-pr-$PRNUMBER.surge.sh/" >> $GITHUB_ENV

      - name: Build                                
        run: hugo --baseURL "${{ env.BASEURL }}"

      - name: Deploy to Surge                            
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: public
          teardown: true
```

However, the handbook uses **Docusaurus**, not Hugo, so we can’t reuse this action directly. Instead, we need to create a similar GitHub Actions workflow that builds the Docusaurus site and deploys it to **Surge (or equivalent)**.

---

## 🛠️ Implementation Plan

1. **Create a new GitHub Actions workflow**

   * Add it at `.github/workflows/deploy-preview.yml`

2. **Replace Hugo with Docusaurus build steps**

   * Use `actions/setup-node` to install Node.js
   * Run `npm ci` to install dependencies
   * Set a dynamic `baseUrl` using the PR number (via `GITHUB_ENV`)
   * Run `npm run build` with the `baseUrl` override (Docusaurus supports this via config or environment variable)

3. **Deploy to Surge (or equivalent)**

   * Use `afc163/surge-preview@v1` or another provider’s deploy action
   * Use `SURGE_TOKEN` (or equivalent) from GitHub Secrets
   * Set `dist` to `build/`, the Docusaurus output directory

4. **Test the flow**

   * Verify that a preview URL is posted on each PR
   * Confirm the preview is accessible with the correct content and base URL

---

## ✅ Acceptance Criteria

* [ ] A GitHub Actions workflow exists at `.github/workflows/deploy-preview.yml`
* [ ] The workflow builds and deploys Docusaurus PRs to Surge (or equivalent)
* [ ] The `baseUrl` is dynamically set based on the PR number
* [ ] Preview links are posted to the pull request
* [ ] Preview URLs follow a format like:
  `https://carletoncomputersciencesociety-handbook-build_preview-pr-XX.surge.sh/` (or equivalent)
* [ ] Secrets are used securely for deploy tokens
